const data = [
  {
    id: '130882',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'A399 Vella 10BK',
    art: '003 ноги 18',
    stock: '1',
    firstPrice: '42268',
    finalPrice: '31701',
    image: './img/161889.jpg',
    // image: './img/130882.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '133793',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'A399 Vella 10BS',
    art: '003 ноги 18',
    stock: '1',
    firstPrice: '42268',
    finalPrice: '31701',
    image: './img/133793.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '163070',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'A399 Vella 15WE-CS',
    art: '008',
    stock: '1',
    firstPrice: '95841',
    finalPrice: '71880.75',
    image: './img/163070.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '163071',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'A399 Vella 15WE-CS',
    art: '003',
    stock: '1',
    firstPrice: '45324',
    finalPrice: '33993',
    image: './img/163071.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '164939',
    showItem: '0',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'A800 70007706',
    art: '385',
    stock: '4',
    firstPrice: '1528',
    finalPrice: '1146',
    image: './img/161889.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '164941',
    showItem: '0',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'A921 70007703 welt 70007706',
    art: '253',
    stock: '1',
    firstPrice: '15074',
    finalPrice: '11305.5',
    image: './img/161889.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '142056',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'accents',
    art: 'A131LN0  tray 40x50x45 walnut',
    stock: '1',
    firstPrice: '8556',
    finalPrice: '6417',
    image: './img/142056.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '142057',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'accents',
    art: 'A130LB0  corner  50x50x45 coffee oak',
    stock: '1',
    firstPrice: '5704',
    finalPrice: '4278',
    image: './img/142057.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '142180',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'accents',
    art: 'A128LB3 OSTUNI COFFEE OAK 75 X120 H33',
    stock: '1',
    firstPrice: '28111',
    finalPrice: '21083.25',
    image: './img/142180.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },

  {
    id: '161889',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'accents',
    art: 'T125LN4  ALBEROBELLO  Coffee table canaletto waltut    80x120xH35',
    stock: '1',
    firstPrice: '32389',
    finalPrice: '24291.75',
    image: './img/161889.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: 'стол'
  },
  {
    id: '163267',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'accents',
    art: 'A130LN0 Noci smoked oak',
    stock: '1',
    firstPrice: '5704',
    finalPrice: '4278',
    image: './img/163267.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  },
  {
    id: '163269',
    showItem: '1',
    factory: 'Natuzzi Editions',
    model: '',
    cover: '',
    description: 'accents',
    art: 'A131LB0 Conversano smoked oak',
    stock: '1',
    firstPrice: '8556',
    finalPrice: '6417',
    image: './img/163269.jpg',
    sizeW: '',
    sizeD: '',
    sizeH: '',
    country: 'Италия',
    tags: ''
  }
]
